variable "tenancy_ocid" {
  description = "OCI tenancy OCID (the root compartment)."
  type        = string
}

variable "region" {
  description = "OCI region used by the lab."
  type        = string
  default     = "us-chicago-1"
}

variable "home_region" {
  description = "OCI tenancy home region used for IAM and Identity Domains control-plane resources."
  type        = string
  validation {
    condition     = can(regex("^[a-z]{2}-[a-z0-9-]+-[0-9]+$", var.home_region))
    error_message = "home_region must be an OCI region identifier such as us-ashburn-1."
  }
}

variable "operator_user_ocid" {
  description = "OCI user OCID from the Deploy Studio config persisted on the registration VM."
  type        = string
  validation {
    condition     = can(regex("^ocid1\\.user\\.", var.operator_user_ocid))
    error_message = "operator_user_ocid must be an OCI user OCID."
  }
}

variable "compartment_ocid" {
  description = "Target compartment already created or resolved by Deploy Studio."
  type        = string
}

variable "objectstorage_namespace" {
  description = "Object Storage namespace resolved by Deploy Studio."
  type        = string
}

variable "deployment_suffix" {
  description = "Optional stable lowercase suffix supplied by Deploy Studio."
  type        = string
  default     = ""
  validation {
    condition     = var.deployment_suffix == "" || can(regex("^[a-z0-9]{4,12}$", var.deployment_suffix))
    error_message = "deployment_suffix must contain 4-12 lowercase letters or digits."
  }
}

variable "admin_username" {
  description = "Local lab administrator username."
  type        = string
  default     = "admin"
  validation {
    condition     = can(regex("^[A-Za-z0-9._-]{3,64}$", var.admin_username))
    error_message = "admin_username must be 3-64 safe username characters."
  }
}

variable "admin_password_hash" {
  description = "PBKDF2 hash generated by Deploy Studio; plaintext is never accepted."
  type        = string
  sensitive   = true
  validation {
    condition     = startswith(var.admin_password_hash, "pbkdf2_sha256$")
    error_message = "admin_password_hash must use the Deploy Studio PBKDF2 format."
  }
}

variable "registration_code_hash" {
  description = "PBKDF2 hash of the normalized registration code."
  type        = string
  sensitive   = true
  validation {
    condition     = startswith(var.registration_code_hash, "pbkdf2_sha256$")
    error_message = "registration_code_hash must use the Deploy Studio PBKDF2 format."
  }
}

variable "preferred_vm_shape" {
  description = "Server-selected E5/E4/E3 Flex shape from the trusted capacity preflight."
  type        = string
  default     = "VM.Standard.E5.Flex"
  validation {
    condition     = contains(["VM.Standard.E5.Flex", "VM.Standard.E4.Flex", "VM.Standard.E3.Flex"], var.preferred_vm_shape)
    error_message = "preferred_vm_shape must be E5 Flex, E4 Flex, or E3 Flex."
  }
}

variable "_oci_instance" {
  description = "Compute defaults aligned with the Select AI Analyzer application host."

  default = {
    shape = {
      name          = "VM.Standard.E5.Flex"
      ocpus         = 2
      memory_in_gbs = 16
    }
  }
}

variable "availability_domain_index" {
  description = "Zero-based availability domain index."
  type        = number
  default     = 0
}

variable "_oci_vcn" {
  description = "VCN defaults aligned with the Select AI Analyzer application host."

  default = {
    cidr_block        = "10.10.0.0/24"
    ingress_tcp_ports = [80, 443]
  }
}

variable "source_repository_url" {
  description = "Trusted public source repository cloned by the VM."
  type        = string
  default     = "https://github.com/jgangini/oci-aidp-cloud-migration-lab.git"
  validation {
    condition     = var.source_repository_url == "https://github.com/jgangini/oci-aidp-cloud-migration-lab.git"
    error_message = "Only the trusted AIDP lab repository is accepted."
  }
}

variable "source_commit_sha" {
  description = "Immutable full source SHA supplied by Deploy Studio."
  type        = string
  validation {
    condition     = can(regex("^[0-9a-f]{40}$", var.source_commit_sha))
    error_message = "source_commit_sha must be a full lowercase Git SHA."
  }
}
