variable "tenancy_ocid" {
  description = "OCI tenancy OCID (the root compartment)."
  type        = string
}

variable "region" {
  description = "OCI region used by the lab."
  type        = string
  default     = "us-chicago-1"
}

variable "home_region" {
  description = "OCI tenancy home region used for IAM and Identity Domains control-plane resources."
  type        = string
  validation {
    condition     = can(regex("^[a-z]{2}-[a-z0-9-]+-[0-9]+$", var.home_region))
    error_message = "home_region must be an OCI region identifier such as us-ashburn-1."
  }
}

variable "compartment_ocid" {
  description = "Target compartment already created or resolved by Deploy Studio."
  type        = string
}

variable "objectstorage_namespace" {
  description = "Object Storage namespace resolved by Deploy Studio."
  type        = string
}

variable "deployment_suffix" {
  description = "Optional stable lowercase suffix supplied by Deploy Studio."
  type        = string
  default     = ""
  validation {
    condition     = var.deployment_suffix == "" || can(regex("^[a-z0-9]{4,12}$", var.deployment_suffix))
    error_message = "deployment_suffix must contain 4-12 lowercase letters or digits."
  }
}

variable "admin_username" {
  description = "Local lab administrator username."
  type        = string
  default     = "admin"
  validation {
    condition     = can(regex("^[A-Za-z0-9._-]{3,64}$", var.admin_username))
    error_message = "admin_username must be 3-64 safe username characters."
  }
}

variable "admin_password_hash" {
  description = "PBKDF2 hash generated by Deploy Studio; plaintext is never accepted."
  type        = string
  sensitive   = true
  validation {
    condition     = startswith(var.admin_password_hash, "pbkdf2_sha256$")
    error_message = "admin_password_hash must use the Deploy Studio PBKDF2 format."
  }
}

variable "registration_code_hash" {
  description = "PBKDF2 hash of the normalized registration code."
  type        = string
  sensitive   = true
  validation {
    condition     = startswith(var.registration_code_hash, "pbkdf2_sha256$")
    error_message = "registration_code_hash must use the Deploy Studio PBKDF2 format."
  }
}

variable "preferred_vm_shape" {
  description = "Explicit flexible VM shape for this APPLY. Retry a capacity failure with E4 through the deploy orchestrator."
  type        = string
  default     = "VM.Standard.E5.Flex"
  validation {
    condition     = contains(["VM.Standard.E5.Flex", "VM.Standard.E4.Flex"], var.preferred_vm_shape)
    error_message = "preferred_vm_shape must be E5 Flex or E4 Flex."
  }
}

variable "vm_ocpus" {
  description = "Flexible VM OCPUs."
  type        = number
  default     = 1
  validation {
    condition     = var.vm_ocpus >= 1 && var.vm_ocpus <= 16
    error_message = "vm_ocpus must be between 1 and 16."
  }
}

variable "vm_memory_gbs" {
  description = "Flexible VM memory in GB."
  type        = number
  default     = 8
  validation {
    condition     = var.vm_memory_gbs >= 8 && var.vm_memory_gbs <= 256
    error_message = "vm_memory_gbs must be between 8 and 256."
  }
}

variable "availability_domain_index" {
  description = "Zero-based availability domain index."
  type        = number
  default     = 0
}

variable "ssh_allowed_cidr" {
  description = "Optional CIDR allowed to SSH. Empty keeps port 22 closed."
  type        = string
  default     = ""
  validation {
    condition     = var.ssh_allowed_cidr == "" || can(cidrnetmask(var.ssh_allowed_cidr))
    error_message = "ssh_allowed_cidr must be empty or a valid CIDR."
  }
}

variable "ssh_public_key" {
  description = "Optional administrator SSH public key."
  type        = string
  default     = ""
  sensitive   = true
}

variable "source_repository_url" {
  description = "Trusted public source repository cloned by the VM."
  type        = string
  default     = "https://github.com/jgangini/oci-aidp-cloud-migration-lab.git"
  validation {
    condition     = var.source_repository_url == "https://github.com/jgangini/oci-aidp-cloud-migration-lab.git"
    error_message = "Only the trusted AIDP lab repository is accepted."
  }
}

variable "source_commit_sha" {
  description = "Immutable full source SHA supplied by Deploy Studio."
  type        = string
  validation {
    condition     = can(regex("^[0-9a-f]{40}$", var.source_commit_sha))
    error_message = "source_commit_sha must be a full lowercase Git SHA."
  }
}
